"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "de" | "en" | "hi"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations for the website
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Common translations
    "app.title": "Digitalisierungsstrategie 2030",
    "app.subtitle": "FORTSCHRITTSBERICHT",
    "nav.dashboard": "Dashboard",
    "nav.progress": "Fortschrittsbericht",
    "nav.monitor": "Monitor",
    "nav.coreProjects": "Kernprojekte",
    "nav.digitalProgress": "Digitale Fortschritte",
    "nav.qualityPerformance": "Qualitative Leistung",
    "nav.healthDigital": "Gesundheit & Digitales",
    "language.select": "Sprache wählen",
    "user.account": "Mein Konto",
    "user.profile": "Profil",
    "user.settings": "Einstellungen",
    "user.logout": "Abmelden",
    "back.overview": "Zurück zur Übersicht",
    "download.report": "Qualitätsbericht herunterladen",
    "footer.contact": "Kontakt: digitalisierung@gesundheit.de | Tel: +49 123 456789",
    "footer.copyright": "© Digitalisierungsstrategie 2030",

    // Dashboard page
    "dashboard.structuralDeficits": "Strukturelle Defizite",
    "dashboard.transformation": "Die Umsetzung digitaler Transformationen",
    "dashboard.deficit1": "Mangelnde Koordination zwischen den verschiedenen Abteilungen führt zu Ineffizienzen",
    "dashboard.deficit2": "Fehlende Standards für den Datenaustausch erschweren die Integration",
    "dashboard.deficit3": "Unzureichende Ressourcen für die Implementierung neuer Technologien",
    "dashboard.potentialValue": "Potenzielle Mehrwerte",
    "dashboard.processOptimization": "Optimierung der Prozesse",
    "dashboard.value1": "Verbesserte Patientenversorgung durch nahtlose Informationsübermittlung",
    "dashboard.value2": "Reduzierung administrativer Aufgaben durch Automatisierung",
    "dashboard.value3": "Erhöhte Datensicherheit und Compliance mit regulatorischen Anforderungen",
    "dashboard.digitalGoals": "Digitale Ziele & Perspektiven",
    "dashboard.longTermStrategy": "Langfristige Strategie",
    "dashboard.goal1": "Entwicklung einer integrierten digitalen Plattform bis 2025",
    "dashboard.goal2": "Implementierung KI-gestützter Diagnosetools zur Unterstützung klinischer Entscheidungen",
    "dashboard.goal3": "Förderung der digitalen Kompetenz aller Mitarbeiter durch Schulungsprogramme",
    "dashboard.currentGuidelines": "Aktuelle Leitlinien",
    "dashboard.guideline1": "Patientenzentrierte Versorgung als Kernprinzip aller digitalen Initiativen",
    "dashboard.guideline2": "Datenschutz und Sicherheit als nicht verhandelbare Grundvoraussetzungen",
    "dashboard.guideline3": "Interoperabilität als Schlüssel zur erfolgreichen digitalen Transformation",
    "dashboard.digitalMaturity": "Digitale Reifung",
    "dashboard.developmentStages": "Entwicklungsstufen",
    "dashboard.maturity1": "Bewertung des aktuellen digitalen Reifegrads der Organisation",
    "dashboard.maturity2": "Identifikation von Schlüsselbereichen für die digitale Weiterentwicklung",
    "dashboard.maturity3": "Entwicklung eines Fahrplans zur Erreichung höherer Reifegradstufen",
    "dashboard.actionAreas": "Aktionsfelder",
    "dashboard.action1": "Digitale Infrastruktur: Ausbau und Modernisierung der IT-Systeme",
    "dashboard.action2": "Digitale Kompetenz: Schulung und Weiterbildung aller Mitarbeiter",
    "dashboard.action3": "Digitale Prozesse: Optimierung und Automatisierung von Arbeitsabläufen",
    "dashboard.digitalizationDegree": "Digitalisierungsgrad",
    "dashboard.currentAssessment":
      "Aktuelle Bewertung der digitalen Reife basierend auf verschiedenen Schlüsselindikatoren",
    "dashboard.infrastructure": "Infrastruktur",
    "dashboard.processDigitalization": "Prozessdigitalisierung",
    "dashboard.viewFullReport": "Vollständigen Bericht ansehen",
    "dashboard.milestones": "Meilensteine",
    "dashboard.phase1": "Phase 1: Analyse",
    "dashboard.phase1Desc":
      "Bestandsaufnahme der aktuellen digitalen Infrastruktur und Identifikation von Schwachstellen",
    "dashboard.phase2": "Phase 2: Konzeption",
    "dashboard.phase2Desc":
      "Entwicklung einer umfassenden Digitalisierungsstrategie mit konkreten Maßnahmen und Zeitplan",
    "dashboard.phase3": "Phase 3: Umsetzung",
    "dashboard.phase3Desc":
      "Schrittweise Implementierung der geplanten Maßnahmen mit regelmäßiger Evaluation des Fortschritts",
    "dashboard.viewDetailedSchedule": "Detaillierten Zeitplan anzeigen",
    "dashboard.dataVisualization": "Datenvisualisierung",
    "dashboard.implementationProgress": "Implementierungsfortschritt",
    "dashboard.resourceAllocation": "Ressourcenverteilung",
    "dashboard.distribution": "Verteilung",
    "dashboard.infrastructurePercent": "Infrastruktur (60%)",
    "dashboard.personnelPercent": "Personal (40%)",
    "dashboard.efficiencyIncrease": "Effizienzsteigerung",
    "dashboard.digitalCompetence": "Digitale Kompetenz",
    "dashboard.medicalStaff": "Ärztliches Personal",
    "dashboard.nursingStaff": "Pflegepersonal",
    "dashboard.administration": "Verwaltung",
    "dashboard.technicalStaff": "Technisches Personal",
    "dashboard.trainingProgram": "Schulungsprogramm",
    "dashboard.trainingDesc":
      "Kontinuierliche Weiterbildung aller Mitarbeiter zur Steigerung der digitalen Kompetenz und optimalen Nutzung der implementierten Systeme.",
    "dashboard.systemUsage": "Systemnutzung",
    "dashboard.electronicPatientRecord": "Elektronische Patientenakte",
    "dashboard.usageRateMedical": "Nutzungsrate durch medizinisches Personal",
    "dashboard.telemedicine": "Telemedizin",
    "dashboard.patientAcceptance": "Akzeptanz bei Patienten",
    "dashboard.digitalDocumentation": "Digitale Dokumentation",
    "dashboard.documentationCompleteness": "Vollständigkeit der Dokumentation",
    "dashboard.patientPortal": "Patientenportal",
    "dashboard.regularUsePatients": "Regelmäßige Nutzung durch Patienten",
    "dashboard.detailedUsageStats": "Detaillierte Nutzungsstatistiken",

    // Core Projects page
    "coreProjects.title": "Kernprojekte",
    "coreProjects.subtitle": "DIGITALE TRANSFORMATION",
    "coreProjects.telemedicine": "Telemedizin",
    "coreProjects.telemed.desc": "Virtuelle Konsultationen und Fernüberwachung",
    "coreProjects.telemed.point1": "Implementierung einer sicheren Videosprechstunden-Plattform",
    "coreProjects.telemed.point2": "Integration von Fernüberwachungssystemen für chronisch kranke Patienten",
    "coreProjects.telemed.point3": "Entwicklung mobiler Anwendungen für die Patientenkommunikation",
    "coreProjects.progress": "Fortschritt",
    "coreProjects.patientPortal": "Patientenportal",
    "coreProjects.portal.desc": "Digitaler Zugang zu Gesundheitsinformationen",
    "coreProjects.portal.point1": "Entwicklung eines benutzerfreundlichen Patientenportals mit sicherem Zugang",
    "coreProjects.portal.point2": "Integration von Terminbuchungssystemen und Erinnerungsfunktionen",
    "coreProjects.portal.point3": "Bereitstellung von personalisierten Gesundheitsinformationen und Ressourcen",
    "coreProjects.electronicRecord": "Elektronische Patientenakte",
    "coreProjects.record.desc": "Zentrale Datenspeicherung und -austausch",
    "coreProjects.record.point1": "Implementierung eines standardisierten elektronischen Patientenaktensystems",
    "coreProjects.record.point2": "Sicherstellung der Interoperabilität mit anderen Gesundheitssystemen",
    "coreProjects.record.point3": "Entwicklung von Datenschutz- und Sicherheitsprotokollen",
    "coreProjects.priority": "Priorität: Hoch",
    "coreProjects.completion": "Geplanter Abschluss: Q2 2024",
    "coreProjects.viewDetailedPlan": "Detaillierten Projektplan ansehen",

    // Digital Progress page
    "digitalProgress.title": "Digitale Fortschritte",
    "digitalProgress.subtitle": "AKTUELLE ENTWICKLUNGEN",
    "digitalProgress.progressReport": "Fortschrittsbericht",
    "digitalProgress.implementationLevel": "Implementierungsgrad",
    "digitalProgress.implementationDesc":
      "Die Implementierung der digitalen Infrastruktur ist zu drei Vierteln abgeschlossen.",
    "digitalProgress.userAcceptance": "Nutzerakzeptanz",
    "digitalProgress.acceptanceDesc": "Die Akzeptanz der neuen digitalen Lösungen unter den Nutzern ist hoch.",
    "digitalProgress.efficiencyIncrease": "Effizienzsteigerung",
    "digitalProgress.efficiencyDesc": "Die Effizienz der Arbeitsprozesse konnte deutlich gesteigert werden.",
    "digitalProgress.developmentOverTime": "Entwicklung über Zeit",
    "digitalProgress.implementation": "Implementierung",
    "digitalProgress.efficiency": "Effizienz",
    "digitalProgress.nextSteps": "Nächste Schritte",
    "digitalProgress.step1": "Erweiterung der digitalen Infrastruktur",
    "digitalProgress.step1Desc": "Ausbau der Serverkapazitäten und Netzwerkinfrastruktur",
    "digitalProgress.step2": "Schulung des Personals",
    "digitalProgress.step2Desc": "Umfassende Schulungsprogramme für alle Mitarbeiterebenen",
    "digitalProgress.step3": "Integration weiterer Systeme",
    "digitalProgress.step3Desc": "Anbindung externer Systeme und Schnittstellen",
    "digitalProgress.schedule": "Zeitplan",
    "digitalProgress.scheduleDesc": "Abschluss aller Maßnahmen bis Ende 2024",
    "digitalProgress.downloadFullReport": "Vollständigen Bericht herunterladen",

    // Quality Performance page
    "quality.title": "Qualitative Leistung",
    "quality.subtitle": "LEISTUNGSKENNZAHLEN",
    "quality.accuracy": "Genauigkeit",
    "quality.accuracyDesc": "Präzision der digitalen Diagnoseunterstützung",
    "quality.responseTime": "Reaktionszeit",
    "quality.responseTimeDesc": "Durchschnittliche Systemantwortzeit",
    "quality.userSatisfaction": "Nutzerzufriedenheit",
    "quality.userSatisfactionDesc": "Bewertung durch medizinisches Personal",

    // Health & Digital page
    "health.title": "Gesundheit & Digitales",
    "health.subtitle": "INTEGRIERTE LÖSUNGEN",
    "health.digitalCare": "Digitale Patientenversorgung",
    "health.priority": "Priorität: Hoch",
    "health.description":
      "Die digitale Patientenversorgung umfasst alle technologischen Lösungen, die zur Verbesserung der Behandlungsqualität und Patientenerfahrung beitragen. Durch den Einsatz digitaler Technologien können Prozesse optimiert, die Kommunikation verbessert und die Versorgungsqualität gesteigert werden.",
    "health.diagnosis": "Diagnose",
    "health.diagnosis.desc":
      "KI-unterstützte Analysen von Patientendaten ermöglichen präzisere und schnellere Diagnosen. Durch die Integration verschiedener Datenquellen können umfassendere Krankheitsbilder erstellt werden.",
    "health.therapy": "Therapie",
    "health.therapy.desc":
      "Personalisierte Therapiepläne basierend auf individuellen Patientendaten führen zu besseren Behandlungsergebnissen. Digitale Tools unterstützen die Therapieüberwachung und -anpassung.",
    "health.aftercare": "Nachsorge",
    "health.aftercare.desc":
      "Digitale Nachsorgeprogramme ermöglichen eine kontinuierliche Betreuung nach der Behandlung. Telemedizinische Lösungen reduzieren unnötige Krankenhausbesuche und verbessern die Patientenzufriedenheit.",
    "health.implementation": "Implementierungsfortschritt",
    "health.diagnosisTools": "Diagnose-Tools",
    "health.therapyManagement": "Therapie-Management",
    "health.aftercarePlatform": "Nachsorge-Plattform",
    "health.benefits": "Vorteile",
    "health.benefit1": "Verbesserte Behandlungsqualität durch präzisere Diagnosen",
    "health.benefit2": "Reduzierte Wartezeiten und administrative Belastung",
    "health.benefit3": "Erhöhte Patientenzufriedenheit durch verbesserte Kommunikation",
    "health.benefit4": "Kosteneffizienz durch optimierte Prozesse",
    "health.nextSteps": "Nächste Schritte",
    "health.q3": "Q3 2023",
    "health.q3.desc": "Abschluss der Implementierung der Diagnose-Tools",
    "health.q4": "Q4 2023",
    "health.q4.desc": "Vollständige Integration des Therapie-Managements",
    "health.q1": "Q1 2024",
    "health.q1.desc": "Launch der digitalen Nachsorge-Plattform",
    "health.detailedInfo": "Detaillierte Projektinformationen",

    // Monitor page
    "monitor.title": "Monitor",
    "monitor.progress": "Fortschritt",
    "monitor.overview": "Übersicht der digitalen Transformation",
    "monitor.implementationPhase": "Implementierungsphase",
    "monitor.digitalInfrastructure": "Digitale Infrastruktur",
    "monitor.modernization": "Modernisierung der IT-Systeme",
    "monitor.phases": "Phasen",
    "monitor.systemIntegration": "Systemintegration",
    "monitor.dataMigration": "Datenmigration",
    "monitor.nextSteps": "Nächste Schritte",
    "monitor.step1": "Abschluss der Systemintegration bis Ende Q3",
    "monitor.step2": "Schulung aller Mitarbeiter bis Ende Q4",
    "monitor.step3": "Vollständige Datenmigration bis Q1 2024",
    "monitor.userAcceptance": "Nutzerakzeptanz",
    "monitor.availability": "Verfügbarkeit",
    "monitor.efficiency": "Effizienz",
    "monitor.viewDetailedReport": "Detaillierten Bericht ansehen",
  },
  en: {
    // Common translations
    "app.title": "Digitalization Strategy 2030",
    "app.subtitle": "PROGRESS REPORT",
    "nav.dashboard": "Dashboard",
    "nav.progress": "Progress Report",
    "nav.monitor": "Monitor",
    "nav.coreProjects": "Core Projects",
    "nav.digitalProgress": "Digital Progress",
    "nav.qualityPerformance": "Quality Performance",
    "nav.healthDigital": "Health & Digital",
    "language.select": "Select Language",
    "user.account": "My Account",
    "user.profile": "Profile",
    "user.settings": "Settings",
    "user.logout": "Logout",
    "back.overview": "Back to Overview",
    "download.report": "Download Quality Report",
    "footer.contact": "Contact: digitalization@health.com | Tel: +49 123 456789",
    "footer.copyright": "© Digitalization Strategy 2030",

    // Dashboard page
    "dashboard.structuralDeficits": "Structural Deficits",
    "dashboard.transformation": "Implementation of digital transformations",
    "dashboard.deficit1": "Lack of coordination between different departments leads to inefficiencies",
    "dashboard.deficit2": "Missing standards for data exchange complicate integration",
    "dashboard.deficit3": "Insufficient resources for implementing new technologies",
    "dashboard.potentialValue": "Potential Value",
    "dashboard.processOptimization": "Process Optimization",
    "dashboard.value1": "Improved patient care through seamless information transfer",
    "dashboard.value2": "Reduction of administrative tasks through automation",
    "dashboard.value3": "Increased data security and compliance with regulatory requirements",
    "dashboard.digitalGoals": "Digital Goals & Perspectives",
    "dashboard.longTermStrategy": "Long-term Strategy",
    "dashboard.goal1": "Development of an integrated digital platform by 2025",
    "dashboard.goal2": "Implementation of AI-supported diagnostic tools to support clinical decisions",
    "dashboard.goal3": "Promotion of digital competence of all employees through training programs",
    "dashboard.currentGuidelines": "Current Guidelines",
    "dashboard.guideline1": "Patient-centered care as the core principle of all digital initiatives",
    "dashboard.guideline2": "Data protection and security as non-negotiable prerequisites",
    "dashboard.guideline3": "Interoperability as the key to successful digital transformation",
    "dashboard.digitalMaturity": "Digital Maturity",
    "dashboard.developmentStages": "Development Stages",
    "dashboard.maturity1": "Assessment of the current digital maturity level of the organization",
    "dashboard.maturity2": "Identification of key areas for digital development",
    "dashboard.maturity3": "Development of a roadmap to achieve higher maturity levels",
    "dashboard.actionAreas": "Action Areas",
    "dashboard.action1": "Digital Infrastructure: Expansion and modernization of IT systems",
    "dashboard.action2": "Digital Competence: Training and education of all employees",
    "dashboard.action3": "Digital Processes: Optimization and automation of workflows",
    "dashboard.digitalizationDegree": "Digitalization Degree",
    "dashboard.currentAssessment": "Current assessment of digital maturity based on various key indicators",
    "dashboard.infrastructure": "Infrastructure",
    "dashboard.processDigitalization": "Process Digitalization",
    "dashboard.viewFullReport": "View Full Report",
    "dashboard.milestones": "Milestones",
    "dashboard.phase1": "Phase 1: Analysis",
    "dashboard.phase1Desc": "Assessment of the current digital infrastructure and identification of weaknesses",
    "dashboard.phase2": "Phase 2: Conception",
    "dashboard.phase2Desc":
      "Development of a comprehensive digitalization strategy with concrete measures and timeline",
    "dashboard.phase3": "Phase 3: Implementation",
    "dashboard.phase3Desc": "Gradual implementation of planned measures with regular evaluation of progress",
    "dashboard.viewDetailedSchedule": "View Detailed Schedule",
    "dashboard.dataVisualization": "Data Visualization",
    "dashboard.implementationProgress": "Implementation Progress",
    "dashboard.resourceAllocation": "Resource Allocation",
    "dashboard.distribution": "Distribution",
    "dashboard.infrastructurePercent": "Infrastructure (60%)",
    "dashboard.personnelPercent": "Personnel (40%)",
    "dashboard.efficiencyIncrease": "Efficiency Increase",
    "dashboard.digitalCompetence": "Digital Competence",
    "dashboard.medicalStaff": "Medical Staff",
    "dashboard.nursingStaff": "Nursing Staff",
    "dashboard.administration": "Administration",
    "dashboard.technicalStaff": "Technical Staff",
    "dashboard.trainingProgram": "Training Program",
    "dashboard.trainingDesc":
      "Continuous education of all employees to increase digital competence and optimal use of implemented systems.",
    "dashboard.systemUsage": "System Usage",
    "dashboard.electronicPatientRecord": "Electronic Patient Record",
    "dashboard.usageRateMedical": "Usage rate by medical staff",
    "dashboard.telemedicine": "Telemedicine",
    "dashboard.patientAcceptance": "Patient acceptance",
    "dashboard.digitalDocumentation": "Digital Documentation",
    "dashboard.documentationCompleteness": "Documentation completeness",
    "dashboard.patientPortal": "Patient Portal",
    "dashboard.regularUsePatients": "Regular use by patients",
    "dashboard.detailedUsageStats": "Detailed Usage Statistics",

    // Core Projects page
    "coreProjects.title": "Core Projects",
    "coreProjects.subtitle": "DIGITAL TRANSFORMATION",
    "coreProjects.telemedicine": "Telemedicine",
    "coreProjects.telemed.desc": "Virtual consultations and remote monitoring",
    "coreProjects.telemed.point1": "Implementation of a secure video consultation platform",
    "coreProjects.telemed.point2": "Integration of remote monitoring systems for chronically ill patients",
    "coreProjects.telemed.point3": "Development of mobile applications for patient communication",
    "coreProjects.progress": "Progress",
    "coreProjects.patientPortal": "Patient Portal",
    "coreProjects.portal.desc": "Digital access to health information",
    "coreProjects.portal.point1": "Development of a user-friendly patient portal with secure access",
    "coreProjects.portal.point2": "Integration of appointment booking systems and reminder functions",
    "coreProjects.portal.point3": "Provision of personalized health information and resources",
    "coreProjects.electronicRecord": "Electronic Patient Record",
    "coreProjects.record.desc": "Central data storage and exchange",
    "coreProjects.record.point1": "Implementation of a standardized electronic patient record system",
    "coreProjects.record.point2": "Ensuring interoperability with other health systems",
    "coreProjects.record.point3": "Development of data protection and security protocols",
    "coreProjects.priority": "Priority: High",
    "coreProjects.completion": "Planned completion: Q2 2024",
    "coreProjects.viewDetailedPlan": "View Detailed Project Plan",

    // Digital Progress page
    "digitalProgress.title": "Digital Progress",
    "digitalProgress.subtitle": "CURRENT DEVELOPMENTS",
    "digitalProgress.progressReport": "Progress Report",
    "digitalProgress.implementationLevel": "Implementation Level",
    "digitalProgress.implementationDesc":
      "The implementation of the digital infrastructure is three-quarters complete.",
    "digitalProgress.userAcceptance": "User Acceptance",
    "digitalProgress.acceptanceDesc": "The acceptance of the new digital solutions among users is high.",
    "digitalProgress.efficiencyIncrease": "Efficiency Increase",
    "digitalProgress.efficiencyDesc": "The efficiency of work processes could be significantly increased.",
    "digitalProgress.developmentOverTime": "Development Over Time",
    "digitalProgress.implementation": "Implementation",
    "digitalProgress.efficiency": "Efficiency",
    "digitalProgress.nextSteps": "Next Steps",
    "digitalProgress.step1": "Expansion of digital infrastructure",
    "digitalProgress.step1Desc": "Expansion of server capacities and network infrastructure",
    "digitalProgress.step2": "Staff training",
    "digitalProgress.step2Desc": "Comprehensive training programs for all employee levels",
    "digitalProgress.step3": "Integration of additional systems",
    "digitalProgress.step3Desc": "Connection of external systems and interfaces",
    "digitalProgress.schedule": "Schedule",
    "digitalProgress.scheduleDesc": "Completion of all measures by the end of 2024",
    "digitalProgress.downloadFullReport": "Download Full Report",

    // Quality Performance page
    "quality.title": "Quality Performance",
    "quality.subtitle": "PERFORMANCE INDICATORS",
    "quality.accuracy": "Accuracy",
    "quality.accuracyDesc": "Precision of digital diagnostic support",
    "quality.responseTime": "Response Time",
    "quality.responseTimeDesc": "Average system response time",
    "quality.userSatisfaction": "User Satisfaction",
    "quality.userSatisfactionDesc": "Rating by medical staff",

    // Health & Digital page
    "health.title": "Health & Digital",
    "health.subtitle": "INTEGRATED SOLUTIONS",
    "health.digitalCare": "Digital Patient Care",
    "health.priority": "Priority: High",
    "health.description":
      "Digital patient care encompasses all technological solutions that contribute to improving treatment quality and patient experience. Through the use of digital technologies, processes can be optimized, communication improved, and quality of care enhanced.",
    "health.diagnosis": "Diagnosis",
    "health.diagnosis.desc":
      "AI-supported analyses of patient data enable more precise and faster diagnoses. By integrating various data sources, more comprehensive clinical pictures can be created.",
    "health.therapy": "Therapy",
    "health.therapy.desc":
      "Personalized therapy plans based on individual patient data lead to better treatment outcomes. Digital tools support therapy monitoring and adjustment.",
    "health.aftercare": "Aftercare",
    "health.aftercare.desc":
      "Digital aftercare programs enable continuous care after treatment. Telemedicine solutions reduce unnecessary hospital visits and improve patient satisfaction.",
    "health.implementation": "Implementation Progress",
    "health.diagnosisTools": "Diagnosis Tools",
    "health.therapyManagement": "Therapy Management",
    "health.aftercarePlatform": "Aftercare Platform",
    "health.benefits": "Benefits",
    "health.benefit1": "Improved treatment quality through more precise diagnoses",
    "health.benefit2": "Reduced waiting times and administrative burden",
    "health.benefit3": "Increased patient satisfaction through improved communication",
    "health.benefit4": "Cost efficiency through optimized processes",
    "health.nextSteps": "Next Steps",
    "health.q3": "Q3 2023",
    "health.q3.desc": "Completion of diagnosis tools implementation",
    "health.q4": "Q4 2023",
    "health.q4.desc": "Complete integration of therapy management",
    "health.q1": "Q1 2024",
    "health.q1.desc": "Launch of digital aftercare platform",
    "health.detailedInfo": "Detailed Project Information",

    // Monitor page
    "monitor.title": "Monitor",
    "monitor.progress": "Progress",
    "monitor.overview": "Overview of digital transformation",
    "monitor.implementationPhase": "Implementation Phase",
    "monitor.digitalInfrastructure": "Digital Infrastructure",
    "monitor.modernization": "Modernization of IT systems",
    "monitor.phases": "Phases",
    "monitor.systemIntegration": "System Integration",
    "monitor.dataMigration": "Data Migration",
    "monitor.nextSteps": "Next Steps",
    "monitor.step1": "Completion of system integration by the end of Q3",
    "monitor.step2": "Training of all employees by the end of Q4",
    "monitor.step3": "Complete data migration by Q1 2024",
    "monitor.userAcceptance": "User Acceptance",
    "monitor.availability": "Availability",
    "monitor.efficiency": "Efficiency",
    "monitor.viewDetailedReport": "View Detailed Report",
  },
  hi: {
    // Common translations
    "app.title": "डिजिटलीकरण रणनीति 2030",
    "app.subtitle": "प्रगति रिपोर्ट",
    "nav.dashboard": "डैशबोर्ड",
    "nav.progress": "प्रगति रिपोर्ट",
    "nav.monitor": "मॉनिटर",
    "nav.coreProjects": "मुख्य परियोजनाएँ",
    "nav.digitalProgress": "डिजिटल प्रगति",
    "nav.qualityPerformance": "गुणवत्ता प्रदर्शन",
    "nav.healthDigital": "स्वास्थ्य और डिजिटल",
    "language.select": "भाषा चुनें",
    "user.account": "मेरा खाता",
    "user.profile": "प्रोफाइल",
    "user.settings": "सेटिंग्स",
    "user.logout": "लॉग आउट",
    "back.overview": "अवलोकन पर वापस जाएं",
    "download.report": "गुणवत्ता रिपोर्ट डाउनलोड करें",
    "footer.contact": "संपर्क: digitalization@health.com | टेल: +49 123 456789",
    "footer.copyright": "© डिजिटलीकरण रणनीति 2030",

    // Dashboard page
    "dashboard.structuralDeficits": "संरचनात्मक कमियां",
    "dashboard.transformation": "डिजिटल परिवर्तनों का कार्यान्वयन",
    "dashboard.deficit1": "विभिन्न विभागों के बीच समन्वय की कमी से अक्षमता होती है",
    "dashboard.deficit2": "डेटा विनिमय के लिए मानकों की कमी एकीकरण को जटिल बनाती है",
    "dashboard.deficit3": "नई तकनीकों को लागू करने के लिए अपर्याप्त संसाधन",
    "dashboard.potentialValue": "संभावित मूल्य",
    "dashboard.processOptimization": "प्रक्रिया अनुकूलन",
    "dashboard.value1": "निर्बाध सूचना हस्तांतरण के माध्यम से बेहतर रोगी देखभाल",
    "dashboard.value2": "स्वचालन के माध्यम से प्रशासनिक कार्यों में कमी",
    "dashboard.value3": "नियामक आवश्यकताओं के साथ बढ़ी हुई डेटा सुरक्षा और अनुपालन",
    "dashboard.digitalGoals": "डिजिटल लक्ष्य और परिप्रेक्ष्य",
    "dashboard.longTermStrategy": "दीर्घकालिक रणनीति",
    "dashboard.goal1": "2025 तक एकीकृत डिजिटल प्लेटफॉर्म का विकास",
    "dashboard.goal2": "नैदानिक निर्णयों का समर्थन करने के लिए एआई-समर्थित नैदानिक उपकरणों का कार्यान्वयन",
    "dashboard.goal3": "प्रशिक्षण कार्यक्रमों के माध्यम से सभी कर्मचारियों की डिजिटल क्षमता का प्रचार",
    "dashboard.currentGuidelines": "वर्तमान दिशानिर्देश",
    "dashboard.guideline1": "सभी डिजिटल पहलों के मूल सिद्धांत के रूप में रोगी-केंद्रित देखभाल",
    "dashboard.guideline2": "डेटा सुरक्षा और सुरक्षा गैर-परक्रामी पूर्वापेक्षाओं के रूप में",
    "dashboard.guideline3": "सफल डिजिटल परिवर्तन की कुंजी के रूप में अंतरसंचालनीयता",
    "dashboard.digitalMaturity": "डिजिटल परिपक्वता",
    "dashboard.developmentStages": "विकास चरण",
    "dashboard.maturity1": "संगठन के वर्तमान डिजिटल परिपक्वता स्तर का आकलन",
    "dashboard.maturity2": "डिजिटल विकास के लिए प्रमुख क्षेत्रों की पहचान",
    "dashboard.maturity3": "उच्च परिपक्वता स्तरों को प्राप्त करने के लिए रोडमैप का विकास",
    "dashboard.actionAreas": "कार्रवाई क्षेत्र",
    "dashboard.action1": "डिजिटल इन्फ्रास्ट्रक्चर: आईटी सिस्टम का विस्तार और आधुनिकीकरण",
    "dashboard.action2": "डिजिटल क्षमता: सभी कर्मचारियों का प्रशिक्षण और शिक्षा",
    "dashboard.action3": "डिजिटल प्रक्रियाएं: कार्यप्रवाह का अनुकूलन और स्वचालन",
    "dashboard.digitalizationDegree": "डिजिटलीकरण की डिग्री",
    "dashboard.currentAssessment": "विभिन्न प्रमुख संकेतकों के आधार पर डिजिटल परिपक्वता का वर्तमान आकलन",
    "dashboard.infrastructure": "बुनियादी ढांचा",
    "dashboard.processDigitalization": "प्रक्रिया डिजिटलीकरण",
    "dashboard.viewFullReport": "पूरी रिपोर्ट देखें",
    "dashboard.milestones": "मील के पत्थर",
    "dashboard.phase1": "चरण 1: विश्लेषण",
    "dashboard.phase1Desc": "वर्तमान डिजिटल बुनियादी ढांचे का आकलन और कमजोरियों की पहचान",
    "dashboard.phase2": "चरण 2: अवधारणा",
    "dashboard.phase2Desc": "ठोस उपायों और समयरेखा के साथ व्यापक डिजिटलीकरण रणनीति का विकास",
    "dashboard.phase3": "चरण 3: कार्यान्वयन",
    "dashboard.phase3Desc": "प्रगति के नियमित मूल्यांकन के साथ योजनाबद्ध उपायों का क्रमिक कार्यान्वयन",
    "dashboard.viewDetailedSchedule": "विस्तृत कार्यक्रम देखें",
    "dashboard.dataVisualization": "डेटा विज़ुअलाइज़ेशन",
    "dashboard.implementationProgress": "कार्यान्वयन प्रगति",
    "dashboard.resourceAllocation": "संसाधन आवंटन",
    "dashboard.distribution": "वितरण",
    "dashboard.infrastructurePercent": "बुनियादी ढांचा (60%)",
    "dashboard.personnelPercent": "कर्मचारी (40%)",
    "dashboard.efficiencyIncrease": "दक्षता वृद्धि",
    "dashboard.digitalCompetence": "डिजिटल क्षमता",
    "dashboard.medicalStaff": "चिकित्सा कर्मचारी",
    "dashboard.nursingStaff": "नर्सिंग कर्मचारी",
    "dashboard.administration": "प्रशासन",
    "dashboard.technicalStaff": "तकनीकी कर्मचारी",
    "dashboard.trainingProgram": "प्रशिक्षण कार्यक्रम",
    "dashboard.trainingDesc":
      "डिजिटल क्षमता बढ़ाने और कार्यान्वित प्रणालियों के इष्टतम उपयोग के लिए सभी कर्मचारियों की निरंतर शिक्षा।",
    "dashboard.systemUsage": "सिस्टम उपयोग",
    "dashboard.electronicPatientRecord": "इलेक्ट्रॉनिक रोगी रिकॉर्ड",
    "dashboard.usageRateMedical": "चिकित्सा कर्मचारियों द्वारा उपयोग दर",
    "dashboard.telemedicine": "टेलीमेडिसिन",
    "dashboard.patientAcceptance": "रोगी स्वीकृति",
    "dashboard.digitalDocumentation": "डिजिटल प्रलेखन",
    "dashboard.documentationCompleteness": "प्रलेखन पूर्णता",
    "dashboard.patientPortal": "रोगी पोर्टल",
    "dashboard.regularUsePatients": "रोगियों द्वारा नियमित उपयोग",
    "dashboard.detailedUsageStats": "विस्तृत उपयोग आंकड़े",

    // Core Projects page
    "coreProjects.title": "मुख्य परियोजनाएँ",
    "coreProjects.subtitle": "डिजिटल परिवर्तन",
    "coreProjects.telemedicine": "टेलीमेडिसिन",
    "coreProjects.telemed.desc": "आभासी परामर्श और दूरस्थ निगरानी",
    "coreProjects.telemed.point1": "सुरक्षित वीडियो परामर्श प्लेटफॉर्म का कार्यान्वयन",
    "coreProjects.telemed.point2": "पुरानी बीमारियों वाले रोगियों के लिए दूरस्थ निगरानी प्रणालियों का एकीकरण",
    "coreProjects.telemed.point3": "रोगी संचार के लिए मोबाइल एप्लिकेशन का विकास",
    "coreProjects.progress": "प्रगति",
    "coreProjects.patientPortal": "रोगी पोर्टल",
    "coreProjects.portal.desc": "स्वास्थ्य जानकारी तक डिजिटल पहुंच",
    "coreProjects.portal.point1": "सुरक्षित पहुंच के साथ उपयोगकर्ता-अनुकूल रोगी पोर्टल का विकास",
    "coreProjects.portal.point2": "अपॉइंटमेंट बुकिंग सिस्टम और रिमाइंडर फंक्शन का एकीकरण",
    "coreProjects.portal.point3": "व्यक्तिगत स्वास्थ्य जानकारी और संसाधनों का प्रावधान",
    "coreProjects.electronicRecord": "इलेक्ट्रॉनिक रोगी रिकॉर्ड",
    "coreProjects.record.desc": "केंद्रीय डेटा भंडारण और विनिमय",
    "coreProjects.record.point1": "मानकीकृत इलेक्ट्रॉनिक रोगी रिकॉर्ड प्रणाली का कार्यान्वयन",
    "coreProjects.record.point2": "अन्य स्वास्थ्य प्रणालियों के साथ अंतरसंचालनीयता सुनिश्चित करना",
    "coreProjects.record.point3": "डेटा सुरक्षा और सुरक्षा प्रोटोकॉल का विकास",
    "coreProjects.priority": "प्राथमिकता: उच्च",
    "coreProjects.completion": "योजनाबद्ध समापन: Q2 2024",
    "coreProjects.viewDetailedPlan": "विस्तृत परियोजना योजना देखें",

    // Digital Progress page
    "digitalProgress.title": "डिजिटल प्रगति",
    "digitalProgress.subtitle": "वर्तमान विकास",
    "digitalProgress.progressReport": "प्रगति रिपोर्ट",
    "digitalProgress.implementationLevel": "कार्यान्वयन स्तर",
    "digitalProgress.implementationDesc": "डिजिटल बुनियादी ढांचे का कार्यान्वयन तीन-चौथाई पूरा हो चुका है।",
    "digitalProgress.userAcceptance": "उपयोगकर्ता स्वीकृति",
    "digitalProgress.acceptanceDesc": "उपयोगकर्ताओं के बीच नए डिजिटल समाधानों की स्वीकृति उच्च है।",
    "digitalProgress.efficiencyIncrease": "दक्षता वृद्धि",
    "digitalProgress.efficiencyDesc": "कार्य प्रक्रियाओं की दक्षता में महत्वपूर्ण वृद्धि हुई है।",
    "digitalProgress.developmentOverTime": "समय के साथ विकास",
    "digitalProgress.implementation": "कार्यान्वयन",
    "digitalProgress.efficiency": "दक्षता",
    "digitalProgress.nextSteps": "अगले कदम",
    "digitalProgress.step1": "डिजिटल बुनियादी ढांचे का विस्तार",
    "digitalProgress.step1Desc": "सर्वर क्षमताओं और नेटवर्क बुनियादी ढांचे का विस्तार",
    "digitalProgress.step2": "कर्मचारी प्रशिक्षण",
    "digitalProgress.step2Desc": "सभी कर्मचारी स्तरों के लिए व्यापक प्रशिक्षण कार्यक्रम",
    "digitalProgress.step3": "अतिरिक्त प्रणालियों का एकीकरण",
    "digitalProgress.step3Desc": "बाहरी प्रणालियों और इंटरफेस का कनेक्शन",
    "digitalProgress.schedule": "कार्यक्रम",
    "digitalProgress.scheduleDesc": "2024 के अंत तक सभी उपायों का समापन",
    "digitalProgress.downloadFullReport": "पूरी रिपोर्ट डाउनलोड करें",

    // Quality Performance page
    "quality.title": "गुणवत्ता प्रदर्शन",
    "quality.subtitle": "प्रदर्शन संकेतक",
    "quality.accuracy": "सटीकता",
    "quality.accuracyDesc": "डिजिटल नैदानिक समर्थन की सटीकता",
    "quality.responseTime": "प्रतिक्रिया समय",
    "quality.responseTimeDesc": "औसत सिस्टम प्रतिक्रिया समय",
    "quality.userSatisfaction": "उपयोगकर्ता संतुष्टि",
    "quality.userSatisfactionDesc": "चिकित्सा कर्मचारियों द्वारा रेटिंग",

    // Health & Digital page
    "health.title": "स्वास्थ्य और डिजिटल",
    "health.subtitle": "एकीकृत समाधान",
    "health.digitalCare": "डिजिटल रोगी देखभाल",
    "health.priority": "प्राथमिकता: उच्च",
    "health.description":
      "डिजिटल रोगी देखभाल में सभी तकनीकी समाधान शामिल हैं जो उपचार की गुणवत्ता और रोगी के अनुभव को बेहतर बनाने में योगदान करते हैं। डिजिटल तकनीकों के उपयोग से प्रक्रियाओं को अनुकूलित किया जा सकता है, संचार में सुधार किया जा सकता है और देखभाल की गुणवत्ता बढ़ाई जा सकती है।",
    "health.diagnosis": "निदान",
    "health.diagnosis.desc":
      "रोगी डेटा के एआई-समर्थित विश्लेषण अधिक सटीक और तेज़ निदान सक्षम करते हैं। विभिन्न डेटा स्रोतों को एकीकृत करके, अधिक व्यापक नैदानिक चित्र बनाए जा सकते हैं।",
    "health.therapy": "चिकित्सा",
    "health.therapy.desc":
      "व्यक्तिगत रोगी डेटा के आधार पर व्यक्तिगत चिकित्सा योजनाएं बेहतर उपचार परिणामों की ओर ले जाती हैं। डिजिटल टूल चिकित्सा निगरानी और समायोजन का समर्थन करते हैं।",
    "health.aftercare": "उपचार के बाद देखभाल",
    "health.aftercare.desc":
      "डिजिटल उपचार के बाद देखभाल कार्यक्रम उपचार के बाद निरंतर देखभाल सक्षम करते हैं। टेलीमेडिसिन समाधान अनावश्यक अस्पताल के दौरे को कम करते हैं और रोगी संतुष्टि में सुधार करते हैं।",
    "health.implementation": "कार्यान्वयन प्रगति",
    "health.diagnosisTools": "निदान उपकरण",
    "health.therapyManagement": "चिकित्सा प्रबंधन",
    "health.aftercarePlatform": "उपचार के बाद देखभाल प्लेटफॉर्म",
    "health.benefits": "लाभ",
    "health.benefit1": "अधिक सटीक निदान के माध्यम से बेहतर उपचार गुणवत्ता",
    "health.benefit2": "कम प्रतीक्षा समय और प्रशासनिक बोझ",
    "health.benefit3": "बेहतर संचार के माध्यम से बढ़ी हुई रोगी संतुष्टि",
    "health.benefit4": "अनुकूलित प्रक्रियाओं के माध्यम से लागत दक्षता",
    "health.nextSteps": "अगले कदम",
    "health.q3": "तिमाही 3 2023",
    "health.q3.desc": "निदान उपकरणों के कार्यान्वयन का पूरा होना",
    "health.q4": "तिमाही 4 2023",
    "health.q4.desc": "चिकित्सा प्रबंधन का पूर्ण एकीकरण",
    "health.q1": "तिमाही 1 2024",
    "health.q1.desc": "डिजिटल उपचार के बाद देखभाल प्लेटफॉर्म का लॉन्च",
    "health.detailedInfo": "विस्तृत परियोजना जानकारी",

    // Monitor page
    "monitor.title": "मॉनिटर",
    "monitor.progress": "प्रगति",
    "monitor.overview": "डिजिटल परिवर्तन का अवलोकन",
    "monitor.implementationPhase": "कार्यान्वयन चरण",
    "monitor.digitalInfrastructure": "डिजिटल बुनियादी ढांचा",
    "monitor.modernization": "आईटी सिस्टम का आधुनिकीकरण",
    "monitor.phases": "चरण",
    "monitor.systemIntegration": "सिस्टम एकीकरण",
    "monitor.dataMigration": "डेटा माइग्रेशन",
    "monitor.nextSteps": "अगले कदम",
    "monitor.step1": "Q3 के अंत तक सिस्टम एकीकरण का पूरा होना",
    "monitor.step2": "Q4 के अंत तक सभी कर्मचारियों का प्रशिक्षण",
    "monitor.step3": "Q1 2024 तक पूर्ण डेटा माइग्रेशन",
    "monitor.userAcceptance": "उपयोगकर्ता स्वीकृति",
    "monitor.availability": "उपलब्धता",
    "monitor.efficiency": "दक्षता",
    "monitor.viewDetailedReport": "विस्तृत रिपोर्ट देखें",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("de")

  // Function to translate text
  const t = (key: string): string => {
    if (!translations[language][key]) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`)
      return key
    }
    return translations[language][key]
  }

  // Store language preference in localStorage
  useEffect(() => {
    if (typeof window !== "undefined") {
      const storedLanguage = localStorage.getItem("language") as Language
      if (storedLanguage && ["de", "en", "hi"].includes(storedLanguage)) {
        setLanguage(storedLanguage)
      }
    }
  }, [])

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("language", language)
      // Set the HTML lang attribute
      document.documentElement.lang = language
    }
  }, [language])

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
